### ISSUE TITLE
Consumed quote indicator broken

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/groupfolders#2332]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
This is a follow up on https://github.com/nextcloud/groupfolders/pull/2244

1. Update to latest release
2. Navigate to Admin settings of Group folder app

### Expected behaviour
The indicator should be in the Quota field

### Actual behaviour
![image](https://user-images.githubusercontent.com/20948931/231997836-57b65b4d-12a9-428d-b6f4-db33d0f68bb5.png)

Replacing https://github.com/nextcloud/groupfolders/blob/0908148fdd87303cc000b10250a5369ee29aa1dd/src/settings/EditSelect.scss#L34-L42

To
```scss
.quotabar {
	margin: 3px 0;
	border-radius: var(--border-radius-large);
	background-color: var(--color-loading-dark);
	height: 34px;
}
```
or 

```scss
.quotabar {
	position: absolute;
	border-radius: var(--border-radius-large);
	top: 0;
	left: 0;
	background-color: var(--color-loading-dark);
	height: 34px;
}
```
(if the absolute positioning is important)

fixes some of the problems
![image](https://user-images.githubusercontent.com/20948931/231999544-9271e3f9-5820-4b78-8858-b283ebc49f75.png)

Open:
- In my opinion `--color-loading-dark` should be replaced by `--color-loading-light` (text otherwise unreadable)
- Small percentages (<~13%) are shown outside the box (probably a problem of the fixed height setting)

No idea of CSS so I don't really have a solution.

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 25.0.5

**Group folders version:** 13.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:** Firefox 112.0.0

**Operating system:** Manjaro

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
